spring.application.name=farmverse-backend
server.port=8081

# H2 Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DataSource Configuration - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/farmverse_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Settings
farmverse.jwt.secret=defaultSecretKeyForFarmVerseBackendSecurity1234567890!
farmverse.jwt.expiration-ms=86400000
